version: '3.9'

x-base-config: &base-config
  image: chatwoot/chatwoot:v4.0.3
  volumes:
    - chatwoot-storage:/app/storage
  networks:
    - dokploy-network
  environment:
    - FRONTEND_URL=${FRONTEND_URL}
    - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    - RAILS_ENV=${RAILS_ENV}
    - NODE_ENV=${NODE_ENV}
    - INSTALLATION_ENV=${INSTALLATION_ENV}
    - RAILS_LOG_TO_STDOUT=${RAILS_LOG_TO_STDOUT}
    - LOG_LEVEL=${LOG_LEVEL}
    - DEFAULT_LOCALE=${DEFAULT_LOCALE}
    - POSTGRES_HOST=${POSTGRES_HOST}
    - POSTGRES_PORT=${POSTGRES_PORT}
    - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    - POSTGRES_USERNAME=${POSTGRES_USERNAME}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - REDIS_URL=${REDIS_URL}
    - ENABLE_ACCOUNT_SIGNUP=${ENABLE_ACCOUNT_SIGNUP}
    - ACTIVE_STORAGE_SERVICE=${ACTIVE_STORAGE_SERVICE}
    - MAILER_DELIVERY_METHOD=${MAILER_DELIVERY_METHOD}
    - MAILER_SENDER_EMAIL=${MAILER_SENDER_EMAIL}
    - SMTP_DOMAIN=${SMTP_DOMAIN}
    - SMTP_ADDRESS=${SMTP_ADDRESS}
    - SMTP_PORT=${SMTP_PORT}
    - SMTP_USERNAME=${SMTP_USERNAME}
    - SMTP_PASSWORD=${SMTP_PASSWORD}
    - SMTP_AUTHENTICATION=${SMTP_AUTHENTICATION}
    - SMTP_ENABLE_STARTTLS_AUTO=${SMTP_ENABLE_STARTTLS_AUTO}
    - SMTP_OPENSSL_VERIFY_MODE=${SMTP_OPENSSL_VERIFY_MODE}
    - MAILER_INBOUND_EMAIL_DOMAIN=${MAILER_INBOUND_EMAIL_DOMAIN}
    - RAILS_INBOUND_EMAIL_SERVICE=${RAILS_INBOUND_EMAIL_SERVICE}
    - RAILS_INBOUND_EMAIL_PASSWORD=${RAILS_INBOUND_EMAIL_PASSWORD}
    - ENABLE_PUSH_RELAY_SERVER=${ENABLE_PUSH_RELAY_SERVER}
    - IOS_APP_ID=${IOS_APP_ID}
    - ANDROID_BUNDLE_ID=${ANDROID_BUNDLE_ID}
    - FORCE_SSL=${FORCE_SSL}
    - ENABLE_RACK_ATTACK=${ENABLE_RACK_ATTACK}
    - ENABLE_RACK_ATTACK_WIDGET_API=${ENABLE_RACK_ATTACK_WIDGET_API}

services:
  chatwoot-rails:
    <<: *base-config
    pull_policy: always
    depends_on:
      chatwoot-postgres:
        condition: service_started
      chatwoot-redis:
        condition: service_started
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'sh', '-c', 'rails db:chatwoot_prepare && rails s -p 3000 -b 0.0.0.0']
    restart: always

  chatwoot-sidekiq:
    <<: *base-config
    pull_policy: always
    depends_on:
      chatwoot-postgres:
        condition: service_started
      chatwoot-redis:
        condition: service_started
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    restart: always

  chatwoot-postgres:
    image: pgvector/pgvector:pg14
    restart: always
    volumes:
      - chatwoot-postgres-data:/var/lib/postgresql/data
      - ./init-vector.sql:/docker-entrypoint-initdb.d/init-vector.sql
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  chatwoot-redis:
    image: redis:alpine
    restart: always
    volumes:
      - chatwoot-redis-data:/data

networks:
  dokploy-network:
    external: true

volumes:
  chatwoot-storage:
  chatwoot-postgres-data:
  chatwoot-redis-data:
